FROM node:16-alpine

WORKDIR /home/node/airbyte
RUN npm install -g npm@7 lerna tsc

COPY package.json package-lock.json ./
RUN sed -i "/jest\|mockttp/d" package.json
COPY ./src ./src
RUN npm install && npm run prepare


RUN ln -s "/home/node/airbyte/bin/main" "/home/node/airbyte/main"
ENV AIRBYTE_ENTRYPOINT "/home/node/airbyte/main"
ENTRYPOINT ["/home/node/airbyte/main"]
